// <auto-generated/>
#pragma warning disable CS0618
using Krafter.Api.Client.Api.TimeTickers.GraphData;
using Krafter.Api.Client.Api.TimeTickers.GraphDataRange;
using Krafter.Api.Client.Api.TimeTickers.SetBatchParent;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Krafter.Api.Client.Api.TimeTickers
{
    /// <summary>
    /// Builds and executes requests for operations under \api\time-tickers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TimeTickersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The GraphData property</summary>
        public global::Krafter.Api.Client.Api.TimeTickers.GraphData.GraphDataRequestBuilder GraphData
        {
            get => new global::Krafter.Api.Client.Api.TimeTickers.GraphData.GraphDataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GraphDataRange property</summary>
        public global::Krafter.Api.Client.Api.TimeTickers.GraphDataRange.GraphDataRangeRequestBuilder GraphDataRange
        {
            get => new global::Krafter.Api.Client.Api.TimeTickers.GraphDataRange.GraphDataRangeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The setBatchParent property</summary>
        public global::Krafter.Api.Client.Api.TimeTickers.SetBatchParent.SetBatchParentRequestBuilder SetBatchParent
        {
            get => new global::Krafter.Api.Client.Api.TimeTickers.SetBatchParent.SetBatchParentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Api.TimeTickers.TimeTickersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TimeTickersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/time-tickers", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Api.TimeTickers.TimeTickersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TimeTickersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/time-tickers", rawUrl)
        {
        }
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Krafter.Api.Client.Api.TimeTickers.TimeTickersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Krafter.Api.Client.Api.TimeTickers.TimeTickersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Krafter.Api.Client.Api.TimeTickers.TimeTickersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TimeTickersRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
