// <auto-generated/>
#pragma warning disable CS0618
using Krafter.Api.Client.Users.ByRole.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Krafter.Api.Client.Users.ByRole
{
    /// <summary>
    /// Builds and executes requests for operations under \users\by-role
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ByRoleRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Krafter.Api.Client.users.byRole.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Krafter.Api.Client.Users.ByRole.Item.WithRoleItemRequestBuilder"/></returns>
        public global::Krafter.Api.Client.Users.ByRole.Item.WithRoleItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("roleId", position);
                return new global::Krafter.Api.Client.Users.ByRole.Item.WithRoleItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Users.ByRole.ByRoleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ByRoleRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users/by-role", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Users.ByRole.ByRoleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ByRoleRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users/by-role", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
