// <auto-generated/>
#pragma warning disable CS0618
using Krafter.Api.Client.Api.CronTickerOccurrences.CronTickerId;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Krafter.Api.Client.Api.CronTickerOccurrences
{
    /// <summary>
    /// Builds and executes requests for operations under \api\cron-ticker-occurrences
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CronTickerOccurrencesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The CronTickerId property</summary>
        public global::Krafter.Api.Client.Api.CronTickerOccurrences.CronTickerId.CronTickerIdRequestBuilder CronTickerId
        {
            get => new global::Krafter.Api.Client.Api.CronTickerOccurrences.CronTickerId.CronTickerIdRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Api.CronTickerOccurrences.CronTickerOccurrencesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CronTickerOccurrencesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/cron-ticker-occurrences", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Api.CronTickerOccurrences.CronTickerOccurrencesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CronTickerOccurrencesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/cron-ticker-occurrences", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
