// <auto-generated/>
#pragma warning disable CS0618
using Krafter.Api.Client.Api;
using Krafter.Api.Client.AppInfo;
using Krafter.Api.Client.ExternalAuth;
using Krafter.Api.Client.Roles;
using Krafter.Api.Client.Tenants;
using Krafter.Api.Client.Tokens;
using Krafter.Api.Client.Users;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Krafter.Api.Client
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class KrafterClient : BaseRequestBuilder
    {
        /// <summary>The api property</summary>
        public global::Krafter.Api.Client.Api.ApiRequestBuilder Api
        {
            get => new global::Krafter.Api.Client.Api.ApiRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The appInfo property</summary>
        public global::Krafter.Api.Client.AppInfo.AppInfoRequestBuilder AppInfo
        {
            get => new global::Krafter.Api.Client.AppInfo.AppInfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The externalAuth property</summary>
        public global::Krafter.Api.Client.ExternalAuth.ExternalAuthRequestBuilder ExternalAuth
        {
            get => new global::Krafter.Api.Client.ExternalAuth.ExternalAuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The roles property</summary>
        public global::Krafter.Api.Client.Roles.RolesRequestBuilder Roles
        {
            get => new global::Krafter.Api.Client.Roles.RolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tenants property</summary>
        public global::Krafter.Api.Client.Tenants.TenantsRequestBuilder Tenants
        {
            get => new global::Krafter.Api.Client.Tenants.TenantsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tokens property</summary>
        public global::Krafter.Api.Client.Tokens.TokensRequestBuilder Tokens
        {
            get => new global::Krafter.Api.Client.Tokens.TokensRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Krafter.Api.Client.Users.UsersRequestBuilder Users
        {
            get => new global::Krafter.Api.Client.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.KrafterClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KrafterClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
