// <auto-generated/>
#pragma warning disable CS0618
using Krafter.Api.Client.Api.CronTicker.Add;
using Krafter.Api.Client.Api.CronTicker.Delete;
using Krafter.Api.Client.Api.CronTicker.Run;
using Krafter.Api.Client.Api.CronTicker.Update;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Krafter.Api.Client.Api.CronTicker
{
    /// <summary>
    /// Builds and executes requests for operations under \api\cron-ticker
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CronTickerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Add property</summary>
        public global::Krafter.Api.Client.Api.CronTicker.Add.AddRequestBuilder Add
        {
            get => new global::Krafter.Api.Client.Api.CronTicker.Add.AddRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The DeletePath property</summary>
        public global::Krafter.Api.Client.Api.CronTicker.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::Krafter.Api.Client.Api.CronTicker.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Run property</summary>
        public global::Krafter.Api.Client.Api.CronTicker.Run.RunRequestBuilder Run
        {
            get => new global::Krafter.Api.Client.Api.CronTicker.Run.RunRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Update property</summary>
        public global::Krafter.Api.Client.Api.CronTicker.Update.UpdateRequestBuilder Update
        {
            get => new global::Krafter.Api.Client.Api.CronTicker.Update.UpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Api.CronTicker.CronTickerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CronTickerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/cron-ticker", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Api.CronTicker.CronTickerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CronTickerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/cron-ticker", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
