// <auto-generated/>
#pragma warning disable CS0618
using Krafter.Api.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Krafter.Api.Client.Users.ByRole.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \users\by-role\{roleId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithRoleItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Users.ByRole.Item.WithRoleItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRoleItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users/by-role/{roleId}?History={History}&IsDeleted={IsDeleted}&MaxResultCount={MaxResultCount}&SkipCount={SkipCount}{&Filter*,Id*,OrderBy*,Query*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Users.ByRole.Item.WithRoleItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRoleItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users/by-role/{roleId}?History={History}&IsDeleted={IsDeleted}&MaxResultCount={MaxResultCount}&SkipCount={SkipCount}{&Filter*,Id*,OrderBy*,Query*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::Krafter.Api.Client.Models.UserInfoPaginationResponseResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Krafter.Api.Client.Models.UserInfoPaginationResponseResponse?> GetAsync(Action<RequestConfiguration<global::Krafter.Api.Client.Users.ByRole.Item.WithRoleItemRequestBuilder.WithRoleItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Krafter.Api.Client.Models.UserInfoPaginationResponseResponse> GetAsync(Action<RequestConfiguration<global::Krafter.Api.Client.Users.ByRole.Item.WithRoleItemRequestBuilder.WithRoleItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Krafter.Api.Client.Models.UserInfoPaginationResponseResponse>(requestInfo, global::Krafter.Api.Client.Models.UserInfoPaginationResponseResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Krafter.Api.Client.Users.ByRole.Item.WithRoleItemRequestBuilder.WithRoleItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Krafter.Api.Client.Users.ByRole.Item.WithRoleItemRequestBuilder.WithRoleItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Krafter.Api.Client.Users.ByRole.Item.WithRoleItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Krafter.Api.Client.Users.ByRole.Item.WithRoleItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Krafter.Api.Client.Users.ByRole.Item.WithRoleItemRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class WithRoleItemRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Filter { get; set; }
#nullable restore
#else
            public string Filter { get; set; }
#endif
            public bool? History { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Id { get; set; }
#nullable restore
#else
            public string Id { get; set; }
#endif
            public bool? IsDeleted { get; set; }
            public int? MaxResultCount { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? OrderBy { get; set; }
#nullable restore
#else
            public string OrderBy { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? Query { get; set; }
#nullable restore
#else
            public string Query { get; set; }
#endif
            public int? SkipCount { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithRoleItemRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Krafter.Api.Client.Users.ByRole.Item.WithRoleItemRequestBuilder.WithRoleItemRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
