// <auto-generated/>
#pragma warning disable CS0618
using Krafter.Api.Client.Users.ByRole;
using Krafter.Api.Client.Users.ChangePassword;
using Krafter.Api.Client.Users.CreateOrUpdate;
using Krafter.Api.Client.Users.Delete;
using Krafter.Api.Client.Users.ForgotPassword;
using Krafter.Api.Client.Users.Get;
using Krafter.Api.Client.Users.GetRoles;
using Krafter.Api.Client.Users.Permissions;
using Krafter.Api.Client.Users.ResetPassword;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Krafter.Api.Client.Users
{
    /// <summary>
    /// Builds and executes requests for operations under \users
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The byRole property</summary>
        public global::Krafter.Api.Client.Users.ByRole.ByRoleRequestBuilder ByRole
        {
            get => new global::Krafter.Api.Client.Users.ByRole.ByRoleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The changePassword property</summary>
        public global::Krafter.Api.Client.Users.ChangePassword.ChangePasswordRequestBuilder ChangePassword
        {
            get => new global::Krafter.Api.Client.Users.ChangePassword.ChangePasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The createOrUpdate property</summary>
        public global::Krafter.Api.Client.Users.CreateOrUpdate.CreateOrUpdateRequestBuilder CreateOrUpdate
        {
            get => new global::Krafter.Api.Client.Users.CreateOrUpdate.CreateOrUpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deletePath property</summary>
        public global::Krafter.Api.Client.Users.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::Krafter.Api.Client.Users.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The forgotPassword property</summary>
        public global::Krafter.Api.Client.Users.ForgotPassword.ForgotPasswordRequestBuilder ForgotPassword
        {
            get => new global::Krafter.Api.Client.Users.ForgotPassword.ForgotPasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getPath property</summary>
        public global::Krafter.Api.Client.Users.Get.GetRequestBuilder GetPath
        {
            get => new global::Krafter.Api.Client.Users.Get.GetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getRoles property</summary>
        public global::Krafter.Api.Client.Users.GetRoles.GetRolesRequestBuilder GetRoles
        {
            get => new global::Krafter.Api.Client.Users.GetRoles.GetRolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The permissions property</summary>
        public global::Krafter.Api.Client.Users.Permissions.PermissionsRequestBuilder Permissions
        {
            get => new global::Krafter.Api.Client.Users.Permissions.PermissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resetPassword property</summary>
        public global::Krafter.Api.Client.Users.ResetPassword.ResetPasswordRequestBuilder ResetPassword
        {
            get => new global::Krafter.Api.Client.Users.ResetPassword.ResetPasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
