// <auto-generated/>
#pragma warning disable CS0618
using Krafter.Api.Client.Api.Ticker.Cancel;
using Krafter.Api.Client.Api.Ticker.Machine;
using Krafter.Api.Client.Api.Ticker.Statuses;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Krafter.Api.Client.Api.Ticker
{
    /// <summary>
    /// Builds and executes requests for operations under \api\ticker
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TickerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Cancel property</summary>
        public global::Krafter.Api.Client.Api.Ticker.Cancel.CancelRequestBuilder Cancel
        {
            get => new global::Krafter.Api.Client.Api.Ticker.Cancel.CancelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The machine property</summary>
        public global::Krafter.Api.Client.Api.Ticker.Machine.MachineRequestBuilder Machine
        {
            get => new global::Krafter.Api.Client.Api.Ticker.Machine.MachineRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The statuses property</summary>
        public global::Krafter.Api.Client.Api.Ticker.Statuses.StatusesRequestBuilder Statuses
        {
            get => new global::Krafter.Api.Client.Api.Ticker.Statuses.StatusesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Api.Ticker.TickerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TickerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/ticker", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Api.Ticker.TickerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TickerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/ticker", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
