// <auto-generated/>
#pragma warning disable CS0618
using Krafter.Api.Client.Api.Ticker.Machine.Jobs;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Krafter.Api.Client.Api.Ticker.Machine
{
    /// <summary>
    /// Builds and executes requests for operations under \api\ticker\machine
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MachineRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Jobs property</summary>
        public global::Krafter.Api.Client.Api.Ticker.Machine.Jobs.JobsRequestBuilder Jobs
        {
            get => new global::Krafter.Api.Client.Api.Ticker.Machine.Jobs.JobsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Api.Ticker.Machine.MachineRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MachineRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/ticker/machine", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Api.Ticker.Machine.MachineRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MachineRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/ticker/machine", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
