// <auto-generated/>
#pragma warning disable CS0618
using Krafter.Api.Client.Roles.GetById.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Krafter.Api.Client.Roles.GetById
{
    /// <summary>
    /// Builds and executes requests for operations under \roles\get-by-id
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetByIdRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Krafter.Api.Client.roles.getById.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Krafter.Api.Client.Roles.GetById.Item.WithRoleItemRequestBuilder"/></returns>
        public global::Krafter.Api.Client.Roles.GetById.Item.WithRoleItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("roleId", position);
                return new global::Krafter.Api.Client.Roles.GetById.Item.WithRoleItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Roles.GetById.GetByIdRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetByIdRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/roles/get-by-id", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Roles.GetById.GetByIdRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetByIdRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/roles/get-by-id", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
