// <auto-generated/>
#pragma warning disable CS0618
using Krafter.Api.Client.ExternalAuth.Google;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Krafter.Api.Client.ExternalAuth
{
    /// <summary>
    /// Builds and executes requests for operations under \external-auth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExternalAuthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The google property</summary>
        public global::Krafter.Api.Client.ExternalAuth.Google.GoogleRequestBuilder Google
        {
            get => new global::Krafter.Api.Client.ExternalAuth.Google.GoogleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.ExternalAuth.ExternalAuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExternalAuthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/external-auth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.ExternalAuth.ExternalAuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExternalAuthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/external-auth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
