// <auto-generated/>
#pragma warning disable CS0618
using Krafter.Api.Client.Api.TimeTicker.Add;
using Krafter.Api.Client.Api.TimeTicker.Delete;
using Krafter.Api.Client.Api.TimeTicker.Update;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Krafter.Api.Client.Api.TimeTicker
{
    /// <summary>
    /// Builds and executes requests for operations under \api\time-ticker
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TimeTickerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Add property</summary>
        public global::Krafter.Api.Client.Api.TimeTicker.Add.AddRequestBuilder Add
        {
            get => new global::Krafter.Api.Client.Api.TimeTicker.Add.AddRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The DeletePath property</summary>
        public global::Krafter.Api.Client.Api.TimeTicker.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::Krafter.Api.Client.Api.TimeTicker.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Update property</summary>
        public global::Krafter.Api.Client.Api.TimeTicker.Update.UpdateRequestBuilder Update
        {
            get => new global::Krafter.Api.Client.Api.TimeTicker.Update.UpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Api.TimeTicker.TimeTickerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TimeTickerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/time-ticker", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Api.TimeTicker.TimeTickerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TimeTickerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/time-ticker", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
