// <auto-generated/>
#pragma warning disable CS0618
using Krafter.Api.Client.Tenants.Create;
using Krafter.Api.Client.Tenants.CreateOrUpdate;
using Krafter.Api.Client.Tenants.Delete;
using Krafter.Api.Client.Tenants.Get;
using Krafter.Api.Client.Tenants.SeedData;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Krafter.Api.Client.Tenants
{
    /// <summary>
    /// Builds and executes requests for operations under \tenants
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TenantsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The create property</summary>
        public global::Krafter.Api.Client.Tenants.Create.CreateRequestBuilder Create
        {
            get => new global::Krafter.Api.Client.Tenants.Create.CreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The createOrUpdate property</summary>
        public global::Krafter.Api.Client.Tenants.CreateOrUpdate.CreateOrUpdateRequestBuilder CreateOrUpdate
        {
            get => new global::Krafter.Api.Client.Tenants.CreateOrUpdate.CreateOrUpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deletePath property</summary>
        public global::Krafter.Api.Client.Tenants.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::Krafter.Api.Client.Tenants.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getPath property</summary>
        public global::Krafter.Api.Client.Tenants.Get.GetRequestBuilder GetPath
        {
            get => new global::Krafter.Api.Client.Tenants.Get.GetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The seedData property</summary>
        public global::Krafter.Api.Client.Tenants.SeedData.SeedDataRequestBuilder SeedData
        {
            get => new global::Krafter.Api.Client.Tenants.SeedData.SeedDataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Tenants.TenantsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TenantsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tenants", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Tenants.TenantsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TenantsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tenants", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
