// <auto-generated/>
#pragma warning disable CS0618
using Krafter.Api.Client.Api.Ticker.Statuses.Get;
using Krafter.Api.Client.Api.Ticker.Statuses.GetLastWeek;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Krafter.Api.Client.Api.Ticker.Statuses
{
    /// <summary>
    /// Builds and executes requests for operations under \api\ticker\statuses
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StatusesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The GetLastWeek property</summary>
        public global::Krafter.Api.Client.Api.Ticker.Statuses.GetLastWeek.GetLastWeekRequestBuilder GetLastWeek
        {
            get => new global::Krafter.Api.Client.Api.Ticker.Statuses.GetLastWeek.GetLastWeekRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The GetPath property</summary>
        public global::Krafter.Api.Client.Api.Ticker.Statuses.Get.GetRequestBuilder GetPath
        {
            get => new global::Krafter.Api.Client.Api.Ticker.Statuses.Get.GetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Api.Ticker.Statuses.StatusesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatusesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/ticker/statuses", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Api.Ticker.Statuses.StatusesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatusesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/ticker/statuses", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
