// <auto-generated/>
#pragma warning disable CS0618
using Krafter.Api.Client.Api.TickerRequest.Id;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Krafter.Api.Client.Api.TickerRequest
{
    /// <summary>
    /// Builds and executes requests for operations under \api\ticker-request
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TickerRequestRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Id property</summary>
        public global::Krafter.Api.Client.Api.TickerRequest.Id.IdRequestBuilder Id
        {
            get => new global::Krafter.Api.Client.Api.TickerRequest.Id.IdRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Api.TickerRequest.TickerRequestRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TickerRequestRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/ticker-request", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Api.TickerRequest.TickerRequestRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TickerRequestRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/ticker-request", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
