// <auto-generated/>
#pragma warning disable CS0618
using Krafter.Api.Client.Api.CronTickerOccurrence.Delete;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Krafter.Api.Client.Api.CronTickerOccurrence
{
    /// <summary>
    /// Builds and executes requests for operations under \api\cron-ticker-occurrence
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CronTickerOccurrenceRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The DeletePath property</summary>
        public global::Krafter.Api.Client.Api.CronTickerOccurrence.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::Krafter.Api.Client.Api.CronTickerOccurrence.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Api.CronTickerOccurrence.CronTickerOccurrenceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CronTickerOccurrenceRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/cron-ticker-occurrence", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Krafter.Api.Client.Api.CronTickerOccurrence.CronTickerOccurrenceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CronTickerOccurrenceRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/cron-ticker-occurrence", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
