// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Krafter.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RoleDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The createdBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Krafter.Api.Client.Models.UserInfo? CreatedBy { get; set; }
#nullable restore
#else
        public global::Krafter.Api.Client.Models.UserInfo CreatedBy { get; set; }
#endif
        /// <summary>The createdById property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedById { get; set; }
#nullable restore
#else
        public string CreatedById { get; set; }
#endif
        /// <summary>The createdOn property</summary>
        public DateTimeOffset? CreatedOn { get; set; }
        /// <summary>The deleteReason property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeleteReason { get; set; }
#nullable restore
#else
        public string DeleteReason { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The isDeleted property</summary>
        public bool? IsDeleted { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The periodEnd property</summary>
        public DateTimeOffset? PeriodEnd { get; set; }
        /// <summary>The periodStart property</summary>
        public DateTimeOffset? PeriodStart { get; set; }
        /// <summary>The permissions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Permissions { get; set; }
#nullable restore
#else
        public List<string> Permissions { get; set; }
#endif
        /// <summary>The recordState property</summary>
        public int? RecordState { get; set; }
        /// <summary>The recordStateRemarks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecordStateRemarks { get; set; }
#nullable restore
#else
        public string RecordStateRemarks { get; set; }
#endif
        /// <summary>The updatedBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Krafter.Api.Client.Models.UserInfo? UpdatedBy { get; set; }
#nullable restore
#else
        public global::Krafter.Api.Client.Models.UserInfo UpdatedBy { get; set; }
#endif
        /// <summary>The updatedById property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedById { get; set; }
#nullable restore
#else
        public string UpdatedById { get; set; }
#endif
        /// <summary>The updatedOn property</summary>
        public DateTimeOffset? UpdatedOn { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Krafter.Api.Client.Models.RoleDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Krafter.Api.Client.Models.RoleDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Krafter.Api.Client.Models.RoleDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdBy", n => { CreatedBy = n.GetObjectValue<global::Krafter.Api.Client.Models.UserInfo>(global::Krafter.Api.Client.Models.UserInfo.CreateFromDiscriminatorValue); } },
                { "createdById", n => { CreatedById = n.GetStringValue(); } },
                { "createdOn", n => { CreatedOn = n.GetDateTimeOffsetValue(); } },
                { "deleteReason", n => { DeleteReason = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "isDeleted", n => { IsDeleted = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "periodEnd", n => { PeriodEnd = n.GetDateTimeOffsetValue(); } },
                { "periodStart", n => { PeriodStart = n.GetDateTimeOffsetValue(); } },
                { "permissions", n => { Permissions = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "recordState", n => { RecordState = n.GetIntValue(); } },
                { "recordStateRemarks", n => { RecordStateRemarks = n.GetStringValue(); } },
                { "updatedBy", n => { UpdatedBy = n.GetObjectValue<global::Krafter.Api.Client.Models.UserInfo>(global::Krafter.Api.Client.Models.UserInfo.CreateFromDiscriminatorValue); } },
                { "updatedById", n => { UpdatedById = n.GetStringValue(); } },
                { "updatedOn", n => { UpdatedOn = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Krafter.Api.Client.Models.UserInfo>("createdBy", CreatedBy);
            writer.WriteStringValue("createdById", CreatedById);
            writer.WriteDateTimeOffsetValue("createdOn", CreatedOn);
            writer.WriteStringValue("deleteReason", DeleteReason);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("isDeleted", IsDeleted);
            writer.WriteStringValue("name", Name);
            writer.WriteDateTimeOffsetValue("periodEnd", PeriodEnd);
            writer.WriteDateTimeOffsetValue("periodStart", PeriodStart);
            writer.WriteCollectionOfPrimitiveValues<string>("permissions", Permissions);
            writer.WriteIntValue("recordState", RecordState);
            writer.WriteStringValue("recordStateRemarks", RecordStateRemarks);
            writer.WriteObjectValue<global::Krafter.Api.Client.Models.UserInfo>("updatedBy", UpdatedBy);
            writer.WriteStringValue("updatedById", UpdatedById);
            writer.WriteDateTimeOffsetValue("updatedOn", UpdatedOn);
        }
    }
}
#pragma warning restore CS0618
