// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Krafter.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SetBatchParentRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The batchRunCondition property</summary>
        public int? BatchRunCondition { get; set; }
        /// <summary>The parentId property</summary>
        public Guid? ParentId { get; set; }
        /// <summary>The targetId property</summary>
        public Guid? TargetId { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Krafter.Api.Client.Models.SetBatchParentRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Krafter.Api.Client.Models.SetBatchParentRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Krafter.Api.Client.Models.SetBatchParentRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "batchRunCondition", n => { BatchRunCondition = n.GetIntValue(); } },
                { "parentId", n => { ParentId = n.GetGuidValue(); } },
                { "targetId", n => { TargetId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("batchRunCondition", BatchRunCondition);
            writer.WriteGuidValue("parentId", ParentId);
            writer.WriteGuidValue("targetId", TargetId);
        }
    }
}
#pragma warning restore CS0618
