// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Krafter.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TenantDtoPaginationResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Krafter.Api.Client.Models.TenantDto>? Items { get; set; }
#nullable restore
#else
        public List<global::Krafter.Api.Client.Models.TenantDto> Items { get; set; }
#endif
        /// <summary>The maxResultCount property</summary>
        public int? MaxResultCount { get; set; }
        /// <summary>The skipCount property</summary>
        public int? SkipCount { get; set; }
        /// <summary>The totalCount property</summary>
        public int? TotalCount { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Krafter.Api.Client.Models.TenantDtoPaginationResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Krafter.Api.Client.Models.TenantDtoPaginationResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Krafter.Api.Client.Models.TenantDtoPaginationResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::Krafter.Api.Client.Models.TenantDto>(global::Krafter.Api.Client.Models.TenantDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "maxResultCount", n => { MaxResultCount = n.GetIntValue(); } },
                { "skipCount", n => { SkipCount = n.GetIntValue(); } },
                { "totalCount", n => { TotalCount = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Krafter.Api.Client.Models.TenantDto>("items", Items);
            writer.WriteIntValue("maxResultCount", MaxResultCount);
            writer.WriteIntValue("skipCount", SkipCount);
            writer.WriteIntValue("totalCount", TotalCount);
        }
    }
}
#pragma warning restore CS0618
