// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Krafter.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TokenResponseResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Krafter.Api.Client.Models.TokenResponse? Data { get; set; }
#nullable restore
#else
        public global::Krafter.Api.Client.Models.TokenResponse Data { get; set; }
#endif
        /// <summary>The error property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Krafter.Api.Client.Models.ErrorResult? Error { get; set; }
#nullable restore
#else
        public global::Krafter.Api.Client.Models.ErrorResult Error { get; set; }
#endif
        /// <summary>The isError property</summary>
        public bool? IsError { get; set; }
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>The statusCode property</summary>
        public int? StatusCode { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Krafter.Api.Client.Models.TokenResponseResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Krafter.Api.Client.Models.TokenResponseResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Krafter.Api.Client.Models.TokenResponseResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "data", n => { Data = n.GetObjectValue<global::Krafter.Api.Client.Models.TokenResponse>(global::Krafter.Api.Client.Models.TokenResponse.CreateFromDiscriminatorValue); } },
                { "error", n => { Error = n.GetObjectValue<global::Krafter.Api.Client.Models.ErrorResult>(global::Krafter.Api.Client.Models.ErrorResult.CreateFromDiscriminatorValue); } },
                { "isError", n => { IsError = n.GetBoolValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "statusCode", n => { StatusCode = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Krafter.Api.Client.Models.TokenResponse>("data", Data);
            writer.WriteObjectValue<global::Krafter.Api.Client.Models.ErrorResult>("error", Error);
            writer.WriteBoolValue("isError", IsError);
            writer.WriteStringValue("message", Message);
            writer.WriteIntValue("statusCode", StatusCode);
        }
    }
}
#pragma warning restore CS0618
